### ISSUE TITLE
Datasets overlay

### ISSUE THREAD

**Issue by cmadjar** [aces/brainbrowser#209]
Overlays of functional and structural images does not super-impose properly. 
  - use world coordinates to overlay volumes?
  - need to do some rotation?

Need to ask Robert on how to do this
![screen shot 2014-11-11 at 3 43 51 pm](https://cloud.githubusercontent.com/assets/1402456/5000424/96645600-69b9-11e4-87b2-ae0717c4d135.png)
.

**Comment by cmadjar** [comment]
Hi,

sorry for the late reply. Actually, these two images come from the same imaging session. While opening them with register or other solftware, they superimpose correctly.

Hope this helps! Thanks for having checked this.

**Comment by rdvincent** [comment]
Fixed as of 5ec9cddc819fdecbc1ab72c95b4f7cef7a1b9ea0
