### ISSUE TITLE
Support for unsigned short images or other types

### ISSUE THREAD

**Issue by juanprietob** [aces/brainbrowser#215]
The current implementation only supports unsigned char images. Moreover, the image intensity values are rescaled. 

To support unsigned short the conversion of the raw stream data must be partitioned using Uint16Array, however, additional work must be done since the image appears saturated. 

The viewer should show the original values without intensity rescaling. 

![screen shot 2014-11-18 at 8 04 04 pm](https://cloud.githubusercontent.com/assets/7086191/5099124/21846f8c-6f5e-11e4-8824-78a5724d2e5a.png)

**Comment by natacha-beck** [comment]
@juanprietob: 
Hi Juan, I just saw that you have closed this issue, is that because we have now in BrainBrowser all the formats you want for the moment, or just is it included in your unmerged PR #252 ? I still have to look at this PR... 

I have the same question for the issue #251.

**Comment by juanprietob** [comment]
Hi Natacha,

I am currently merging the master branch to my fork.
Those two issues have been resolved.

I have started working with ITK readers compiled in javascript in order to
read multiple image types.
I will expand on this when I push the merged code again.

**Comment by natacha-beck** [comment]
@juanprietob Oh nice, I hope that the merge will work fine, and I´m impatient to see the new PR.

**Comment by juanprietob** [comment]
My version has diverted quite a lot. 
Specially in panel.js. 
I think we will have to review the changes.
