### ISSUE TITLE
Unable to upload vertex data files to Surface Viewer

### ISSUE THREAD

**Issue by zijdenbos** [aces/brainbrowser#258]
The Surface Viewer from BrainBrowser at https://brainbrowser.cbrain.mcgill.ca/surface-viewer#ct does not seem to be able to load per-vertex data using the "standard" .txt files (ASCII, since value/vertex) used within the MINC toolset. When selecting Per-Vertex Data, the options are "MNI OBJ", "Freesurfer Binary" and "Freesurfer ASC". None of these seem to be able to recognize and upload .txt for rendering the values on the surface. 

I am fairly sure this used to work in previous versions.

**Comment by natacha-beck** [comment]
Fixed by @rdvincent  the issue was on the web-service side. 
Should be ok now.
