### ISSUE TITLE
Public release ?

### ISSUE THREAD

**Issue by natacha-beck** [aces/brainbrowser#273]
Since Bert have made lot of improvement on Brainbrowser we should think to do a public release.

**Comment by tsherif** [comment]
Do it!

These changes look interesting. I want to see them on the website.

**Comment by bryan-kc** [comment]
I have been following this project for quite some time and am quite excited to see the updates.

**Comment by rdvincent** [comment]
I have a few more P.R.'s before I think the new overlay is ready. Shouldn't take long.

**Comment by rdvincent** [comment]
@natacha-beck What do we need to do to make a new release?
