### ISSUE TITLE
Brain orientation

### ISSUE THREAD

**Issue by MounaSafiHarab** [aces/brainbrowser#295]
Brain orientation is posterior on top/anterior at the bottom for the axial plan (screenshot can be provided or obtained from redmine 9387, BrainOrientation.png); the other way around would be clearer (anterior at the top and posterior at the bottom)

**Comment by rdvincent** [comment]
I don't seem to have access to that issue on redmine (is it LORIS-specific?). The brain orientation is normally anterior at the top, so this case is probably either an old problem, or an unusual file. Can we track down the file against which this was reported and see if the problem still exists?

**Comment by MounaSafiHarab** [comment]
@rdvincent,

yes it is a Loris task (there is only a .png file there, no minc, no DICOM). I am guessing it is an unusual file (because the conversion to mnc was done recently), so I will try to get you the DICOM file.

**Comment by MounaSafiHarab** [comment]
@rdvincent ,

I followed up with the person who reported this issue. She has not experienced this problem again and she can not seem to find the problematic DICOM (she did not document the candidate that had this issue properly). She will let us know if she comes across the issue again. Meanwhile, please feel free to close this issue.
