### ISSUE TITLE
Support for for GifTI

### ISSUE THREAD

**Issue by chrisfilo** [aces/brainbrowser#321]
Currently BrainBrowser Surface viewer support binary and asc (text) file formats used internally by FreeSurfer. GifTI is a more standardized way of storing surface information (both in terms of surface shape as well as values on vertices). It would be a great addition if BrainBrowser supported GifTI surfaces, scalars and label maps. Both freesurfer (freeview and tkviewer) as well as the connectome workbench both support GIfTI. More about the format: https://www.nitrc.org/projects/gifti/

**Comment by rdvincent** [comment]
@chrisfilo Thanks for the suggestion. I'm not aware of any pure-Javascript implementations of GIfTI, are you?

**Comment by chrisfilo** [comment]
There is this: https://github.com/rii-mango/GIFTI-Reader-JS

**Comment by chrisfilo** [comment]
I see you started working on it. That's fantastic. Would it help if I tried to test it?

**Comment by rdvincent** [comment]
Sure. Just check out the rdv-gifti branch on:

https://github.com/rdvincent/brainbrowser

It seems to work ok for the GIFTI surfaces I have; it is also possible to read vertex data. My biggest problem is a low diversity of GIFTI sample images.

**Comment by chrisfilo** [comment]
Attached some examples I have been working with. I'm interested in plotting lh.sig.shape.gii on top of lh.pial.surf.gii.

[fsaverage_examples_small.zip](https://github.com/aces/brainbrowser/files/578977/fsaverage_examples_small.zip)

**Comment by rdvincent** [comment]
Those images seem to work fine as single pairs. I'm not happy with how the two shape files interact when both are loaded, but I suspect a generic brainbrowser issue.

FYI mni-display can now visualize GIFTI surfaces and I have recently added shape and label data.

**Comment by chrisfilo** [comment]
I experience similar problems before gifti support when loading left and right inflated surfaces at the same time (the shape origin was not offset and the two shapes overlapped). It wasn't present when I loaded pial or white surfaces. It would be nice to get that sorted out. I'll try to provide some screenshots.

Thanks for the heads up about mni-display. I'm working on support for surface data in neurovault.org and this reassures me that going with GifTI downloads maximizes compatibility with existing software.

**Comment by rdvincent** [comment]
My experience with GIFTI so far is that the coordinate system is inconsistently defined from file to file - that's the biggest weakness of the surface format that I've encountered. For example, the two surface files you just uploaded do not contain coordinate transforms.

**Comment by chrisfilo** [comment]
I can confirm the gifti support is working correctly. Thanks!
