### ISSUE TITLE
Brain Browser Overlay Issue

### ISSUE THREAD

**Issue by mohadesz** [aces/brainbrowser#325]
When using BrainBrowser with an overlay, the brain in the axial plan is not centred properly (the sagittal and coronal views are fine).  It looks good in the individual scan view, but the overlay is shifted at the bottom of the "box".
![unnamed](https://cloud.githubusercontent.com/assets/508561/23083906/faa3b910-f52d-11e6-94fe-e47f1a610a05.png)

There are two MINC volumes (an email will be sent separately) resulting in an off/not centred overlay in the axial plan.  These are matching. PIANO processed T1 and AV45 PET volumes (biospective_589335_BL*.mnc) in stx space

**Comment by natacha-beck** [comment]
@mohadesz: I did not get any of your file at this point, it could be nice to have it in order to play with it.

**Comment by natacha-beck** [comment]
@mohadesz 

You seems to have 2 different issues in your issue.

The first on about the off/on overlay, I tried to reproduce the bug and I see nothing special even with your files: 

![bio](https://cloud.githubusercontent.com/assets/777590/23804691/f6ba7a80-0588-11e7-918b-213b0577869a.png)

If you really have issue with this, just let me know and give me more detail. 

For the second issue about the color map, for me it make no sense to use color map on a mask. What do you think guys ? @rdvincent and @jonathanlurie
