### ISSUE TITLE
How to change to radiological conventions

### ISSUE THREAD

**Issue by taylersindhu** [aces/brainbrowser#357]
Is there a way to change display to radiological conventions (i.e. LAS)?
I suspect it is via some modification of the volume-loaders (e.g mgh.js).
Thanks for your help!

**Comment by taylersindhu** [comment]
More specifically, how are where can we implement the following code?:
BrainBrowser.VolumeViewer.utils.flipArray(image_data, 256, 256, { flipx: true });

**Comment by taylersindhu** [comment]
If it is helpful:
https://nipy.org/nibabel/neuro_radio_conventions.html

**Comment by taylersindhu** [comment]
Edit: Some progress with matrix multiplication of the "transform" variable in mgh.js and nifti1.js (for .mgh and .nii inputs).

**Comment by natacha-beck** [comment]
Happy to hear that. 
Can you please point us to your code, it seems to be a very good option to add to BrainBrowser.

**Comment by taylersindhu** [comment]
Hi Natacha- I am able to switch left-right, but still having issues positioning the anterior aspect screen right on sagittal view. I have reached out to a few colleagues and will get back to you if I find a consistent fix.
